// import React, { useEffect, useRef } from "react";
// import { ChevronDown, HelpCircle } from "lucide-react";
// import { motion } from "framer-motion";

// const FAQ_ITEMS = [
//   {
//     imgSrc: "/Website-Images/FAQ-Images/Commission-Structure.png",
//     imgAlt: "Commission 3D",
//     accentColor: "#7c3aed",
//     borderColor: "rgba(124,58,237,0.45)",
//     cardGlow: "0 0 55px 8px rgba(124,58,237,0.18)",
//     dotGradient: ["rgba(126,34,204,0.62)", "rgba(21,22,68,0.82)"],
//     dotBorder: "rgba(213,92,255,0.78)",
//     dotShadow: "0 0 28px rgba(204,80,255,0.36)",
//     iconColor: "#d98cff",
//     q: "How does the commission structure work?",
//     a: "We charge a 1% commission only on deals that close through leads generated by our platform. This ensures we're aligned with your success.",
//   },
//   {
//     imgSrc: "/Website-Images/FAQ-Images/Customize-Avatar.png",
//     imgAlt: "Avatar Customize 3D",
//     accentColor: "#7c3aed",
//     borderColor: "rgba(124,58,237,0.45)",
//     cardGlow: "0 0 55px 8px rgba(124,58,237,0.18)",
//     dotGradient: ["rgba(9,126,204,0.5)", "rgba(13,30,75,0.84)"],
//     dotBorder: "rgba(47,207,255,0.78)",
//     dotShadow: "0 0 28px rgba(47,207,255,0.32)",
//     iconColor: "#74f4ff",
//     q: "Can I customize my avatars?",
//     a: "Yes! All plans include avatar customization. Professional and Enterprise plans offer advanced training and personality customization options.",
//   },
//   {
//     imgSrc: "/Website-Images/FAQ-Images/CRM.png",
//     imgAlt: "CRM 3D",
//     accentColor: "#06b6d4",
//     borderColor: "rgba(6,182,212,0.40)",
//     cardGlow: "0 0 55px 8px rgba(6,182,212,0.16)",
//     dotGradient: ["rgba(9,126,204,0.5)", "rgba(13,30,75,0.84)"],
//     dotBorder: "rgba(47,207,255,0.78)",
//     dotShadow: "0 0 28px rgba(47,207,255,0.32)",
//     iconColor: "#74f4ff",
//     q: "What CRM integrations are available?",
//     a: "We integrate with HubSpot, Salesforce, Zoho, and most major real estate CRMs. Enterprise plans include custom integration development.",
//   },
//   {
//     imgSrc: "/Website-Images/FAQ-Images/Free-Trial.png",
//     imgAlt: "Free Trial 3D",
//     accentColor: "#7c3aed",
//     borderColor: "rgba(124,58,237,0.45)",
//     cardGlow: "0 0 55px 8px rgba(124,58,237,0.18)",
//     dotGradient: ["rgba(126,34,204,0.62)", "rgba(21,22,68,0.82)"],
//     dotBorder: "rgba(213,92,255,0.78)",
//     dotShadow: "0 0 28px rgba(204,80,255,0.36)",
//     iconColor: "#d98cff",
//     q: "Is there a free trial?",
//     a: "Yes! Start with a 14-day free trial on any plan. No credit card required to begin.",
//   },
// ];

// const FAQ: React.FC = () => {
//   const sectionRef  = useRef<HTMLDivElement>(null);
//   const titleRef    = useRef<HTMLHeadingElement>(null);
//   const faqItemsRef = useRef<(HTMLDivElement | null)[]>([]);

//   return (
//     <div
//       ref={sectionRef}
//       className="relative overflow-hidden w-full"
//     >
//       <style>{`
//         @import url('https://fonts.googleapis.com/css2?family=Syne:wght@700;800;900&family=Sora:wght@400;500;600;700&display=swap');
//         @keyframes shimmer-faq { 0%,100%{background-position:0%} 50%{background-position:100%} }
//         .hf { font-family:'Syne',sans-serif; }
//         .bf { font-family:'Sora',sans-serif; }
//         .faq-container {
//           max-width: 1200px;
//           margin: 0 auto;
//           padding: clamp(60px, 8vw, 100px) clamp(16px, 4vw, 48px);
//         }
//         .faq-header-grid {
//           display: grid;
//           grid-template-columns: minmax(140px, 240px) minmax(0, 1fr) minmax(140px, 240px);
//           align-items: center;
//           gap: clamp(18px, 3vw, 32px);
//         }
//         .faq-side-art {
//           width: clamp(150px, 18vw, 240px);
//           height: clamp(150px, 18vw, 240px);
//         }
//         .faq-row-grid {
//           display: grid;
//           grid-template-columns: minmax(180px, 240px) 2px minmax(0, 1fr) 88px;
//           align-items: center;
//         }
//         .faq-image-cell {
//           min-height: clamp(130px, 18vw, 160px);
//         }
//         .faq-card-image {
//           width: clamp(132px, 18vw, 190px);
//           height: clamp(104px, 14vw, 150px);
//         }
//         @media (max-width: 1024px) {
//           .faq-header-grid {
//             grid-template-columns: 1fr;
//           }
//           .faq-side-wrap {
//             display: none;
//           }
//           .faq-row-grid {
//             grid-template-columns: minmax(150px, 210px) minmax(0, 1fr);
//           }
//           .faq-divider,
//           .faq-chevron {
//             display: none;
//           }
//         }
//         @media (max-width: 640px) {
//           .faq-container {
//             padding-top: 60px;
//             padding-bottom: 60px;
//           }
//           .faq-badge {
//             width: 100%;
//             justify-content: center;
//             gap: 10px;
//             padding-inline: 14px;
//             font-size: 12px;
//           }
//           .faq-row-grid {
//             grid-template-columns: 1fr;
//           }
//           .faq-card {
//             border-radius: 18px !important;
//           }
//           .faq-image-cell {
//             min-height: 128px;
//             padding: 16px;
//           }
//           .faq-card-image {
//             width: min(170px, 56vw);
//             height: auto;
//             max-height: 128px;
//           }
//           .faq-text-cell {
//             padding: 18px 18px 22px !important;
//             text-align: center;
//           }
//         }
//       `}</style>

//       {/* ── Radial glows — same as Hero ── */}
      

//       <div className="faq-container relative z-10">

//         {/* ══════════════════════════
//             HEADER
//         ══════════════════════════ */}
//         <div className="text-center mb-16 relative">

//           {/* Badge */}
//           <div
//             className="faq-badge bf inline-flex items-center gap-3 rounded-full px-5 py-2 text-sm font-bold text-white mb-8"
//             style={{
//               background: "linear-gradient(90deg,rgba(91,25,176,0.72),rgba(15,27,78,0.72))",
//               border: "1.5px solid rgba(155,91,255,0.75)",
//               boxShadow: "0 0 26px rgba(119,61,255,0.50), inset 0 0 16px rgba(255,255,255,0.08)",
//             }}
//           >
//             <span className="flex h-8 w-8 items-center justify-center rounded-lg"
//               style={{ background: "linear-gradient(135deg,#d35cff,#6335ff)", boxShadow: "0 0 18px rgba(199,86,255,0.70)" }}>
//               <HelpCircle className="h-5 w-5 text-white" strokeWidth={2.6} />
//             </span>
//             Got Questions? We've Got Answers!
//           </div>

//           {/* Three-col layout: left 3D image | heading | right 3D image */}
//           <div className="faq-header-grid relative">

//             {/* Left 3D image */}
//             <div className="faq-side-wrap flex justify-center items-end">
//               <img
//                 src="/Website-Images/FAQ-Images/QuestionMark.png"
//                 alt="FAQ Question Mark 3D"
//                 draggable={false}
//                 className="faq-side-art object-contain select-none"
//                 style={{
//                   filter: "drop-shadow(0 0 36px rgba(124,58,237,0.65)) drop-shadow(0 8px 24px rgba(0,0,0,0.60))",
//                   userSelect: "none",
//                 } as React.CSSProperties}
//               />
//             </div>

//             {/* Heading */}
//             <div ref={titleRef}>
//               <h2
//                 className="hf font-black leading-[0.98] text-white"
//                 style={{ fontSize: "clamp(2.45rem,5.8vw,4rem)", textShadow: "0 10px 40px rgba(0,0,0,0.50)" }}
//               >
//                 Frequently Asked
//                 <span
//                   className="block mt-1"
//                   style={{
//                     background: "linear-gradient(90deg,#d65dff 0%,#8d58ff 48%,#28cfff 100%)",
//                     backgroundSize: "200%",
//                     WebkitBackgroundClip: "text",
//                     WebkitTextFillColor: "transparent",
//                     backgroundClip: "text",
//                     animation: "shimmer-faq 4s ease infinite",
//                     filter: "drop-shadow(0 0 20px rgba(91,160,255,0.40))",
//                   }}
//                 >
//                   Questions
//                 </span>
//               </h2>

//               <p className="bf mt-5 leading-relaxed max-w-lg mx-auto"
//                 style={{ color: "rgba(255,255,255,0.60)", fontSize: "clamp(0.92rem,1.5vw,1.1rem)" }}>
//                 Everything you need to know about our pricing and features
//               </p>

//               {/* gradient underline */}
//               <div className="mx-auto mt-5 h-1.5 w-24 rounded-full"
//                 style={{ background: "linear-gradient(90deg,#ca46ff,#31c8ff)", boxShadow: "0 0 18px rgba(86,174,255,0.60)" }} />
//             </div>

//             {/* Right 3D image */}
//             <div className="faq-side-wrap flex justify-center items-end">
//               <img
//                 src="/Website-Images/FAQ-Images/Checklist.png"
//                 alt="FAQ Checklist 3D"
//                 draggable={false}
//                 className="faq-side-art object-contain select-none"
//                 style={{
//                   filter: "drop-shadow(0 0 36px rgba(6,182,212,0.55)) drop-shadow(0 8px 24px rgba(0,0,0,0.60))",
//                   userSelect: "none",
//                 } as React.CSSProperties}
//               />
//             </div>
//           </div>
//         </div>

//         {/* ══════════════════════════
//             FAQ ROWS
//         ══════════════════════════ */}
//         <div className="flex flex-col gap-5 max-w-6xl mx-auto">
//           {FAQ_ITEMS.map((faq, i) => (
//             <motion.div
//               key={faq.q}
//               ref={el => { faqItemsRef.current[i] = el; }}
//               whileHover={{ scale: 1.012, borderColor: `${faq.accentColor}` }}
//               transition={{ duration: 0.2 }}
//               className="faq-card group cursor-default overflow-hidden rounded-[24px]"
//               style={{
//                 background: "linear-gradient(105deg,rgba(56,12,99,0.50) 0%,rgba(8,15,48,0.92) 42%,rgba(3,26,63,0.88) 100%)",
//                 border: `1.5px solid ${faq.borderColor}`,
//                 backdropFilter: "blur(18px)",
//                 boxShadow: `${faq.cardGlow}, 0 18px 54px rgba(0,0,0,0.38), inset 0 1px 0 rgba(255,255,255,0.07)`,
//               }}
//             >
//               <div className="faq-row-grid">

//                 {/* ── LEFT: 3D image cell ── */}
//                 <div
//                   className="faq-image-cell relative flex items-center justify-center py-5 px-4"
//                   style={{
//                     background: i % 2 === 0
//                       ? "linear-gradient(145deg,rgba(140,52,255,0.13),rgba(43,171,255,0.08))"
//                       : "linear-gradient(145deg,rgba(56,199,255,0.08),rgba(156,63,255,0.13))",
//                   }}
//                 >
//                   {/* ambient glow behind image */}
//                   <div className="absolute inset-0 pointer-events-none"
//                     style={{
//                       background: `radial-gradient(ellipse 70% 70% at 50% 60%, ${faq.accentColor}20 0%, transparent 70%)`,
//                     }} />
//                   <img
//                     src={faq.imgSrc}
//                     alt={faq.imgAlt}
//                     draggable={false}
//                     onContextMenu={e => e.preventDefault()}
//                     className="faq-card-image relative z-10 object-contain select-none"
//                     style={{
//                       userSelect: "none",
//                       filter: `drop-shadow(0 0 22px ${faq.accentColor}70) drop-shadow(0 6px 18px rgba(0,0,0,0.60))`,
//                     } as React.CSSProperties}
//                   />
//                 </div>

//                 {/* ── Vertical divider ── */}
//                 <div className="faq-divider self-stretch"
//                   style={{
//                     width: "2px",
//                     background: "linear-gradient(180deg,#d75cff,#33c9ff)",
//                     boxShadow: "0 0 16px rgba(117,119,255,0.62)",
//                     margin: "24px 0",
//                   }} />

//                 {/* ── Text ── */}
//                 <div className="faq-text-cell px-7 py-6 lg:py-0 lg:pr-8">
//                   <h3 className="hf font-black text-white mb-3 leading-tight"
//                     style={{ fontSize: "clamp(1.1rem,1.5vw,1.5rem)", textShadow: "0 4px 16px rgba(0,0,0,0.40)" }}>
//                     {faq.q}
//                   </h3>
//                   <p className="bf leading-relaxed"
//                     style={{ color: "rgba(255,255,255,0.72)", fontSize: "clamp(0.9rem,1.2vw,1rem)" }}>
//                     {faq.a}
//                   </p>
//                 </div>

//                 {/* ── Chevron circle ── */}
//                 <div className="faq-chevron flex justify-center items-center pr-6">
//                   <span
//                     className="flex h-16 w-16 items-center justify-center rounded-full transition-transform duration-200 group-hover:scale-105"
//                     style={{
//                       background: `linear-gradient(145deg,${faq.dotGradient[0]},${faq.dotGradient[1]})`,
//                       border: `1.5px solid ${faq.dotBorder}`,
//                       boxShadow: `${faq.dotShadow}, inset 0 0 18px rgba(255,255,255,0.08)`,
//                     }}
//                   >
//                     <ChevronDown className="h-7 w-7" style={{ color: faq.iconColor }} strokeWidth={3} />
//                   </span>
//                 </div>
//               </div>
//             </motion.div>
//           ))}
//         </div>

//       </div>
//     </div>
//   );
// };

// export default FAQ;


import React, { useState } from "react";
import { ChevronDown, HelpCircle } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

// ─────────────────────────────────────────────
// FAQ data (images removed — only Q & A + theming)
// ─────────────────────────────────────────────
const FAQ_ITEMS = [
  {
    accentColor: "#7c3aed",
    borderColor: "rgba(124,58,237,0.45)",
    cardGlow:    "0 0 55px 8px rgba(124,58,237,0.18)",
    dotGradient: ["rgba(126,34,204,0.62)", "rgba(21,22,68,0.82)"],
    dotBorder:   "rgba(213,92,255,0.78)",
    dotShadow:   "0 0 28px rgba(204,80,255,0.36)",
    iconColor:   "#d98cff",
    q: "How does the commission structure work?",
    a: "We charge a 1% commission only on deals that close through leads generated by our platform. This ensures we're aligned with your success.",
  },
  {
    accentColor: "#06b6d4",
    borderColor: "rgba(6,182,212,0.40)",
    cardGlow:    "0 0 55px 8px rgba(6,182,212,0.16)",
    dotGradient: ["rgba(9,126,204,0.5)", "rgba(13,30,75,0.84)"],
    dotBorder:   "rgba(47,207,255,0.78)",
    dotShadow:   "0 0 28px rgba(47,207,255,0.32)",
    iconColor:   "#74f4ff",
    q: "Can I customize my avatars?",
    a: "Yes! All plans include avatar customization. Professional and Enterprise plans offer advanced training and personality customization options.",
  },
  {
    accentColor: "#06b6d4",
    borderColor: "rgba(6,182,212,0.40)",
    cardGlow:    "0 0 55px 8px rgba(6,182,212,0.16)",
    dotGradient: ["rgba(9,126,204,0.5)", "rgba(13,30,75,0.84)"],
    dotBorder:   "rgba(47,207,255,0.78)",
    dotShadow:   "0 0 28px rgba(47,207,255,0.32)",
    iconColor:   "#74f4ff",
    q: "What CRM integrations are available?",
    a: "We integrate with HubSpot, Salesforce, Zoho, and most major real estate CRMs. Enterprise plans include custom integration development.",
  },
  {
    accentColor: "#7c3aed",
    borderColor: "rgba(124,58,237,0.45)",
    cardGlow:    "0 0 55px 8px rgba(124,58,237,0.18)",
    dotGradient: ["rgba(126,34,204,0.62)", "rgba(21,22,68,0.82)"],
    dotBorder:   "rgba(213,92,255,0.78)",
    dotShadow:   "0 0 28px rgba(204,80,255,0.36)",
    iconColor:   "#d98cff",
    q: "Is there a free trial?",
    a: "Yes! Start with a 14-day free trial on any plan. No credit card required to begin.",
  },
];

const FAQ: React.FC = () => {
  // null = sab closed. Number = wahi index open hai.
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  const toggle = (i: number) => setOpenIndex(prev => (prev === i ? null : i));

  return (
    <div
      className="relative overflow-hidden w-full flex items-center justify-center"
      style={{ minHeight: "100vh" }}
    >
      <style>{`
        @keyframes shimmer-faq { 0%,100%{background-position:0%} 50%{background-position:100%} }

        .faq-container {
          width: 100%;
          max-width: min(920px, 92vw);
          margin: 0 auto;
          padding: clamp(28px, 4vh, 64px) clamp(14px, 4vw, 48px);
        }
        @media (max-width: 380px) {
          .faq-container { padding: 32px 12px; }
        }
        @media (min-width: 1920px) {
          .faq-container { max-width: 1080px; }
        }

        .faq-card-btn {
          width: 100%;
          display: flex;
          align-items: center;
          gap: clamp(14px, 1.8vw, 22px);
          padding: clamp(14px, 1.8vh, 20px) clamp(20px, 2.4vw, 28px);
          background: transparent;
          border: none;
          text-align: left;
          cursor: pointer;
          color: inherit;
          font: inherit;
        }
        .faq-card-btn:focus-visible {
          outline: 2px solid rgba(167,139,250,0.7);
          outline-offset: -2px;
          border-radius: inherit;
        }

        @media (max-width: 640px) {
          .faq-container { padding: 40px 16px; }
          .faq-badge {
            width: 100%;
            justify-content: center;
            gap: 10px;
            padding-inline: 14px;
            font-size: 11px;
          }
          .faq-card { border-radius: 16px !important; }
        }
      `}</style>

      <div className="faq-container relative z-10">

        {/* ══════════════════════════
            HEADER (centered, no side images)
        ══════════════════════════ */}
        <div className="text-center mb-8 lg:mb-10">

          {/* Badge */}
          <div
            className="faq-badge bf landing-eyebrow inline-flex items-center gap-2.5 rounded-full px-4 py-2 font-bold text-white mb-6"
            style={{
              background: "linear-gradient(90deg,rgba(91,25,176,0.72),rgba(15,27,78,0.72))",
              border: "1.5px solid rgba(155,91,255,0.75)",
              boxShadow: "0 0 26px rgba(119,61,255,0.50), inset 0 0 16px rgba(255,255,255,0.08)",
            }}
          >
            <span className="flex h-7 w-7 items-center justify-center rounded-lg"
              style={{ background: "linear-gradient(135deg,#d35cff,#6335ff)", boxShadow: "0 0 18px rgba(199,86,255,0.70)" }}>
              <HelpCircle className="h-4 w-4 text-white" strokeWidth={2.6} />
            </span>
            Got Questions? We've Got Answers!
          </div>

          {/* Heading */}
          <motion.div
            initial={{ opacity: 0, y: 60, rotateX: 30 }}
            whileInView={{ opacity: 1, y: 0, rotateX: 0 }}
            viewport={{ once: true, amount: 0.3 }}
            transition={{ duration: 1.0, ease: "easeOut" }}
          >
            <h2
              className="hf landing-title text-white"
              style={{ textShadow: "0 10px 40px rgba(0,0,0,0.50)" }}
            >
              Frequently Asked{" "}
              <span
                style={{
                  background: "linear-gradient(90deg,#d65dff 0%,#8d58ff 48%,#28cfff 100%)",
                  backgroundSize: "200%",
                  WebkitBackgroundClip: "text",
                  WebkitTextFillColor: "transparent",
                  backgroundClip: "text",
                  animation: "shimmer-faq 4s ease infinite",
                  filter: "drop-shadow(0 0 20px rgba(91,160,255,0.40))",
                }}
              >
                Questions
              </span>
            </h2>

            <p className="bf landing-description mt-4 max-w-xl mx-auto"
              style={{ color: "rgba(255,255,255,0.75)" }}>
              Everything you need to know about our pricing and features
            </p>

            <div className="mx-auto mt-4 h-1 w-20 rounded-full"
              style={{ background: "linear-gradient(90deg,#ca46ff,#31c8ff)", boxShadow: "0 0 18px rgba(86,174,255,0.60)" }} />
          </motion.div>
        </div>

        {/* ══════════════════════════
            FAQ ACCORDION
        ══════════════════════════ */}
        <div className="flex flex-col gap-3">
          {FAQ_ITEMS.map((faq, i) => {
            const isOpen = openIndex === i;
            return (
              <motion.div
                key={faq.q}
                initial={{ opacity: 0, y: 30, scale: 0.97 }}
                whileInView={{ opacity: 1, y: 0, scale: 1 }}
                viewport={{ once: true, amount: 0.2 }}
                animate={{
                  borderColor: isOpen ? faq.accentColor : faq.borderColor,
                }}
                transition={{ duration: 0.6, ease: "easeOut", delay: i * 0.08 }}
                className="faq-card group overflow-hidden rounded-[18px]"
                style={{
                  background: "linear-gradient(105deg,rgba(56,12,99,0.50) 0%,rgba(8,15,48,0.92) 42%,rgba(3,26,63,0.88) 100%)",
                  border: `1.5px solid ${faq.borderColor}`,
                  backdropFilter: "blur(18px)",
                  boxShadow: `${faq.cardGlow}, 0 14px 40px rgba(0,0,0,0.38), inset 0 1px 0 rgba(255,255,255,0.07)`,
                }}
              >
                {/* ── Clickable header (the Question row) ── */}
                <button
                  type="button"
                  className="faq-card-btn"
                  onClick={() => toggle(i)}
                  aria-expanded={isOpen}
                  aria-controls={`faq-panel-${i}`}
                >
                  <h3
                    className="hf landing-card-title text-white flex-1"
                    style={{
                      textShadow: "0 4px 16px rgba(0,0,0,0.40)",
                    }}
                  >
                    {faq.q}
                  </h3>

                  {/* Chevron — rotates on open */}
                  <motion.span
                    animate={{ rotate: isOpen ? 180 : 0 }}
                    transition={{ duration: 0.3, ease: "easeOut" }}
                    className="flex items-center justify-center rounded-full shrink-0"
                    style={{
                      width:  "clamp(40px, 3.2vw, 48px)",
                      height: "clamp(40px, 3.2vw, 48px)",
                      background: `linear-gradient(145deg,${faq.dotGradient[0]},${faq.dotGradient[1]})`,
                      border:     `1.5px solid ${faq.dotBorder}`,
                      boxShadow:  `${faq.dotShadow}, inset 0 0 18px rgba(255,255,255,0.08)`,
                    }}
                  >
                    <ChevronDown
                      style={{ color: faq.iconColor, width: "clamp(18px, 1.5vw, 22px)", height: "clamp(18px, 1.5vw, 22px)" }}
                      strokeWidth={3}
                    />
                  </motion.span>
                </button>

                {/* ── Collapsible Answer panel ── */}
                <AnimatePresence initial={false}>
                  {isOpen && (
                    <motion.div
                      key="answer"
                      id={`faq-panel-${i}`}
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{
                        height:  { duration: 0.32, ease: [0.4, 0, 0.2, 1] },
                        opacity: { duration: 0.25, ease: "easeOut" },
                      }}
                      style={{ overflow: "hidden" }}
                    >
                      <div style={{ padding: "0 clamp(18px, 2.2vw, 26px) clamp(12px, 1.6vh, 18px)" }}>
                        {/* gradient separator */}
                        <div
                          className="w-full mb-3"
                          style={{
                            height: "1px",
                            background: `linear-gradient(90deg, transparent, ${faq.accentColor}aa, transparent)`,
                          }}
                        />
                        <p
                          className="bf landing-card-description"
                          style={{
                            color:    "rgba(255,255,255,0.82)",
                          }}
                        >
                          {faq.a}
                        </p>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            );
          })}
        </div>

      </div>
    </div>
  );
};

export default FAQ;